version: '3'

services:
  web:
    build: .
    command: bash -c "uvicorn app.main:app --host 127.0.0.1 --port 8008 --reload"
    ports:
      - "8008:8008"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: "redis:alpine"