version: '3'

services:
  app:
    build:
      context: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
